name: JackHenryCodeExercise Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dependencies
      run: dotnet restore
      working-directory: JackHenryCodeExercise/
    - name: Build
      run: dotnet build JackHenryCodeExercise.sln --no-restore
    - name: Test
      run: dotnet test JackHenryCodeExercise.sln --no-build --verbosity normal