name: JackHenryCodeExercise Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dependencies
      run: dotnet restore
      working-directory: JackHenryCodeExercise/JackHenryCodeExercise/
    - name: Build
      run: dotnet build JackHenryCodeExercise.sln --no-restore
    - name: Test
      run: dotnet test JackHenryCodeExercise.sln --no-build --verbosity normal
